# Linear independence {#linear-independence}

Recall the homogeneous equation $\mathbf{A} \mathbf{x} = \mathbf{0}$ can be written as a linear combination of coefficients $x_1, \ldots, x_K$ and vectors $\mathbf{a}_1, \ldots, \mathbf{a}_K$ where 
$$
\begin{align*}
\sum_{k=1}^K x_k \mathbf{a}_k = \mathbf{0}
\end{align*}
$$
```{definition} 
The set of vectors $\mathbf{a}_1, \ldots, \mathbf{a}_K$ are called **linearly independent** if the only solution to the vector equation $\sum_{k=1}^K x_k \mathbf{a}_k = \mathbf{0}$ is the trivial solution. The set of vectors $\mathbf{a}_1, \ldots, \mathbf{a}_K$ are called **linearly dependent** if there are coefficients $x_1, \ldots, x_K$ that are not all zero.
```

* **Example: in class**

* What does it mean for a set of vectors to be **linearly dependent**? This means that there is at least one vector $\mathbf{a}_k$ that can be written as a sum of the other vectors with coefficients $z_k$:
$$
\begin{align*}
\mathbf{a}_k = \sum_{k' \neq k} z_{k'} \mathbf{a}_{k'}
\end{align*}
$$
Note: this does not imply that all vectors $\mathbf{a}_{k}$ can be written as a linear combination of other vectors.

* **Example: in class -- determine if the vectors are linearly independent and solve the dependence relation**

```{theorem} 
The matrix equation $\mathbf{A}$ has linearly independent columns if and only if the equation $\mathbf{A}\mathbf{x} = \mathbf{0}$ has only the trivial solution.
```

* **Example: in class** A set of a single vector

* **Example:  in class** A set of two vectors

    * linearly independent if:
    
    * linearly dependent if one vector is a scalar multiple of the other:
    
    
```{theorem}
If an $n \times K$ matrix $\mathbf{A}$ has $K > n$, then the columns of $\mathbf{A}$ are linearly dependent. In other words, if a set of vectors $\mathbf{a}_1, \ldots, \mathbf{a}_K$ contains more vectors than entries within vectors, the set of vectors is linearly dependent.
```

* **Proof:** If $K>n$, there are more variables ($K$) than equations ($n$). Therefore, there is at least one free variable and this implies that the homogeneous equation $\mathbf{A}\mathbf{x}=\mathbf{0}$ has a non-trivial solution \@ref(eq:homogeneous)


```{theorem}
If a set of vectors $\mathbf{a}_1, \ldots, \mathbf{a}_K$ contains the $\mathbf{0}$ vector, then the the set of vectors is linearly dependent.
```

* **Proof: in class**

* **Example: in class** Determine whether the following sets of vectors are linearly dependent






    
    




