{
  "hash": "1bf6a52f7e9900f9b7552bc88b892bea",
  "result": {
    "markdown": "#  Vector Spaces and Subspaces\n\n\n\n- [3 Blue 1 Brown -- Abstract vector spaces](https://www.3blue1brown.com/lessons/abstract-vector-spaces)\n\n\n\n::: {.cell}\n\n:::\n\n\nRecall the definition of a subspace:\n\n::: {.definition}\nA subspace $\\mathcal{H}$ of a vector space $\\mathcal{V}$ is a subset of $\\mathcal{V}$ such that\n\n* $\\mathcal{H}$ contains the zero vector -- $\\mathbf{0} \\in \\mathcal{H}$\n\n* $\\mathcal{H}$ is closed under vector addition. Therefore, for $\\mathbf{u}$ and $\\mathbf{v}$ in $\\mathcal{H}$, the sum $\\mathbf{u} + \\mathbf{v}$ is in $\\mathcal{H}$\n\n* $\\mathcal{H}$ is closed under scalar multiplication. Therefore, for $\\mathbf{u}$ in $\\mathcal{H}$ and a scalar $a$, the product $a \\mathbf{u}$ is in $\\mathcal{H}$\n:::\n\nA consequence of this definition is that a subspace $\\mathcal{H}$ is closed under linear combinations. \n\n\n## Null space and column space\n\nAlso, recall the special subspaces of the column space and the null space. \n\n\n### Null space\n\n::: {.definition}\nThe null space null($\\mathbf{A}$) of an $m \\times n$ $\\mathbf{A}$ is the set of all solutions of the homogeneous equation $\\mathbf{A} \\mathbf{x} = \\mathbf{0}$\n\nAnother way to write null($\\mathbf{A}$) is \n\n$$\n\\begin{aligned}\n\\mbox{null}(\\mathbf{A}) = \\{\\mathbf{x} : \\mathbf{x} \\in \\mathcal{R}^n \\mbox{ and } \\mathbf{A} \\mathbf{x} = \\mathbf{0} \\}\n\\end{aligned}\n$$\n\n:::\n\n\n\n:::{#thm-}\nThe null space of an $m \\times n$ matrix $\\mathbf{A}$ is a subspace of $\\mathcal{R}^n$.\n:::\n\n\n\n::: {.callout-tip icon=false collapse=\"true\" appearance=\"simple\"} \n## Proof\n\nTo show that the null space of $\\mathbf{A}$, denoted null($\\mathbf{A})$, is a subspace we need to show the following\n\n1) The zero vector $\\mathbf{0}$ is in the null space of $\\mathbf{A}$\n\n2) The null space of $\\mathbf{A}$ is closed under addition\n\n3) The null space of $\\mathbf{A}$ is closed under scalar multiplication\n\nThe null space of $\\mathbf{A}$ is defined as the set of vectors $\\mathbf{x}$ such that $\\mathbf{A} \\mathbf{x} = \\mathbf{0}$. \n\n1) First, we show that the zero vector is in the subspace by setting $\\mathbf{x} = \\mathbf{0}$. Thus, because $\\mathbf{A} \\mathbf{0} = \\mathbf{0}$, the zero vector $\\mathbf{0}$ is in the null space of $\\mathbf{A}$ .\n\n2) Next, let $\\mathbf{u}$ and $\\mathbf{v}$ be vectors in the null space of $\\mathbf{A}$. Thus, by the definition of the null space we have $\\mathbf{A} \\mathbf{u} = \\mathbf{0}$ and $\\mathbf{A} \\mathbf{v} = \\mathbf{0}$. Consider the vector $\\mathbf{u} + \\mathbf{v}$ and consider $\\mathbf{A} (\\mathbf{u} + \\mathbf{v}) = \\mathbf{A} \\mathbf{u} + \\mathbf{A} \\mathbf{v} = \\mathbf{0} + \\mathbf{0} = \\mathbf{0}$. Thus $\\mathbf{u} + \\mathbf{v}$ is in the null space of $\\mathbf{A}$.\n\n3) Finally, let $\\mathbf{u}$ be a vector in the null space of $\\mathbf{A}$ and let $c$ be a scalar. Thus, by the definition of the null space we have $\\mathbf{A} \\mathbf{u} = \\mathbf{0}$. Then, consider $\\mathbf{A} (c \\mathbf{u}) = c \\mathbf{A} \\mathbf{u} = c \\mathbf{0} = \\mathbf{0}$\n\nBecause the three requirements for a subspace are met, this gives us that the null space of $\\mathbf{A}$ is a subspace.\n:::\n\n\nAs a consequence, there will exist a set of vectors that span the null space null($\\mathbf{A}$). However, the null space of $\\mathbf{A}$ is defined implicitly. This means that the null space of $\\mathbf{A}$ is not obvious given the vectors of $\\mathbf{A}$ and must be checked/calculated.\n\n::: {#exm-}\n* In class\n\nFind a spanning set for null($\\mathbf{A}$) where\n\n\n$$\n\\begin{aligned}\n\\mathbf{A} = \\begin{pmatrix} 7 & -2 & 7 & -4 & 5 \\\\ 2 & 0 & 3 & 3 & 9 \\\\ -5 & 2 & -5 & 7 & -2 \\end{pmatrix}\n\\end{aligned}\n$$\n\n\n* Find solution to system of homogeneous system of equations $\\mathbf{A} \\mathbf{x} = \\mathbf{0}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA <- matrix(c(7, 2, -5, -2, 0, 2, 7, 3, -5, -4, 3, 7, 5, 9, -2), 3, 5)\nrref(cbind(A, 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3] [,4]  [,5] [,6]\n[1,]    1    0    0 1.50 -4.50    0\n[2,]    0    1    0 7.25  2.75    0\n[3,]    0    0    1 0.00  6.00    0\n```\n:::\n:::\n\n\n* Take the general solution and write as a linear combination of vectors where the coefficients are the free variables.\n\n* general solution $x_1 = -1.5 x_4 + 4.5 x_5$, $x_2 = -7.25 x_4 - 2.75 x_5$, $x_3 = -6 x_5$ and both $x_4$ and $x_5$ are free. Write out the general solution in vector form.\n\n\n$$\n\\begin{aligned}\n\\begin{pmatrix} x_1 \\\\ x_2 \\\\ x_3 \\\\ x_4 \\\\ x_5 \\end{pmatrix} = \\begin{pmatrix} -1.5 x_4 + 4.5 x_5\\\\ -7.25 x_4 - 2.75 x_5 \\\\ -6 x_5 \\\\ x_4 \\\\ x_5 \\end{pmatrix} = x_4 \\begin{pmatrix} -1.5 \\\\ -7.25 \\\\ 0 \\\\ 1 \\\\ 0 \\end{pmatrix} + x_5 \\begin{pmatrix} 4.5 \\\\ 2.75 \\\\ -6 \\\\ 0 \\\\ 1 \\end{pmatrix}\n\\end{aligned}\n$$\n\n\n* From above, the free variables $x_4$ and $x_5$ are multiplied by the vectors $\\mathbf{u} =  \\begin{pmatrix} -1.5 \\\\ -7.25 \\\\ 0 \\\\ 1 \\\\ 0 \\end{pmatrix}$ and $\\mathbf{v} = \\begin{pmatrix} 4.5 \\\\ 2.75 \\\\ -6 \\\\ 0 \\\\ 1 \\end{pmatrix}$ where $\\{ \\mathbf{u}, \\mathbf{v} \\}$ are a spanning set for the null($\\mathbf{A}$)\n\n:::\n\n::: {#exm-}\n* In class -- do another\nFind a spanning set for null($\\mathbf{A}$) where\n\n:::\n\n\n\n### Column space\n\n::: {.definition}\nThe columns space col($\\mathbf{A}$) of an $m \\times n$ $\\mathbf{A}$ is the set of all linear combinations of the columns of $\\mathbf{A}$. \n\nIf $\\{ \\mathbf{a}_1, \\ldots, \\mathbf{a}_n\\}$ are the columns of $\\mathbf{A}$, then \n\n$$\n\\begin{aligned}\n\\mbox{col}(\\mathbf{A}) = \\mbox{span}(\\mathbf{A})\n\\end{aligned}\n$$\n\nthis can be written in set notation as \n\n$$\n\\begin{aligned}\n\\mbox{col}(\\mathbf{A}) = \\{ \\mathbf{b} : \\mathbf{A} \\mathbf{x} = \\mathbf{b} \\mbox{ for some } \\mathbf{x} \\in \\mathcal{R}^n \\}\n\\end{aligned}\n$$\n\n:::\n\n:::{#thm-}\nThe column space of an $m \\times n$ matrix $\\mathbf{A}$ is a subspace of $\\mathcal{R}^n$.\n:::\n\n::: {.callout-tip icon=false collapse=\"true\" appearance=\"simple\"} \n## Proof\n\nDo in class\n\n* $\\mathbf{0}$ vector\n\n* sum of vectors\n\n* scalar multiplication\n:::\n\n\nCompared to the null space, the column space is defined explicitly--it is the span of the columns of $\\mathbf{A}$. The definition of the column space results in the fact that col($\\mathbf{A}$) is the range of the linear transformation $\\mathbf{x} \\rightarrow \\mathbf{A} \\mathbf{x}$.\n\n::: {#exm-}\n* In class\n\nFind a spanning set for col($\\mathbf{A}$) where\n\n\n$$\n\\begin{aligned}\n\\mathbf{A} = \\begin{pmatrix} 6 & 0 & 4 \\\\ 5 & -1 & -9 \\\\ -4 & 7 & 4 \\\\ 6 & 2 & 9 \\end{pmatrix}\n\\end{aligned}\n$$\n\n:::\n\n\n### Understanding the differerneces between the column space and the null space\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./images/null-column.jpg){width=100%}\n:::\n:::\n",
    "supporting": [
      "14-vector-spaces-and-subspaces_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}