on:
  push:
     branches:
       - master


name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest

    env:
      RENV_PATHS_ROOT: ~/Library/Application Support/renv

    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-tinytex@master
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install X11 dependencies on MacOS
        if: runner.os == 'macOS'
        run: brew install --cask xquartz
      
      - name: Install magick, libgit2, and poppler using homebrew
        run: |
          brew install imagemagick@6
          brew install libgit2
          brew install poppler       
          
      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore R packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::consent(provided = TRUE)'
          R -e 'renv::restore()'

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-          
          
      - name: Render Book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@3.0.0
       env:
         GITHUB_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens:  
       with: 
          email: ${{ secrets.EMAIL }}               # must be a verified email
          build_dir: _book/                     # "_site/" by default
